import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Categories from "./components/Categories";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <script src="https://kit.fontawesome.com/4f91921791.js" async></script>
      <body className={`bg-[#8D8D6C] w-full h-screen font-sans`}>
        <Header />
        <Categories />
        {children}
        <Footer />
      </body>
    </html>
  );
}
